name: pinn311
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - anyio=4.7.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h827c3e9_1
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.4=py311haa95532_0
  - attrs=24.3.0=py311haa95532_0
  - babel=2.16.0=py311haa95532_0
  - beautifulsoup4=4.12.3=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py311haa95532_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - certifi=2025.4.26=py311haa95532_0
  - cffi=1.17.1=py311h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - debugpy=1.8.11=py311h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.17.0=py311haa95532_0
  - freeglut=3.4.0=hd77b12b_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - h11=0.14.0=py311haa95532_0
  - httpcore=1.0.2=py311haa95532_0
  - httpx=0.28.1=py311haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py311haa95532_1
  - ipython=9.1.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - ipywidgets=8.1.5=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=py311haa95532_0
  - jsonschema=4.23.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.7.2=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.15.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.3.4=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.27.3=py311haa95532_0
  - jupyterlab_widgets=3.0.13=py311haa95532_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.7.0=h404307b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=h18467be_1
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-base=3.10.0=py311he19b0ae_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - narwhals=1.31.0=py311haa95532_1
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.4.2=py311haa95532_0
  - notebook=7.3.2=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numpy=2.0.1=py311hdab7c0b_1
  - numpy-base=2.0.1=py311hd01c5d8_1
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.16=h3f729d1_0
  - overrides=7.4.0=py311haa95532_0
  - packaging=24.2=py311haa95532_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py311haa95532_0
  - pillow=11.1.0=py311hea0d53e_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py311haa95532_0
  - plotly=6.0.1=py311hbc747e5_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.43=py311haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h827c3e9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py311haa95532_0
  - pyqt=6.7.1=py311h5da7b33_1
  - pyqt6-sip=13.9.1=py311h827c3e9_1
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.11=h4607a30_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-json-logger=3.2.1=py311haa95532_0
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=308=py311h5da7b33_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=26.2.0=py311h5da7b33_0
  - qtbase=6.7.3=h0804d20_0
  - qtconsole=5.6.1=py311haa95532_1
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtpy=2.4.1=py311haa95532_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.32.3=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=78.1.1=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.0=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py311haa95532_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.5=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.12.2=py311haa95532_0
  - typing_extensions=4.12.2=py311haa95532_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - urllib3=2.3.0=py311haa95532_0
  - vc=14.42=haa95532_5
  - vs2015_runtime=14.42.34433=hbfb602d_5
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.13=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
    - absl-py==2.3.0
    - aiobotocore==2.22.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.0
    - aioitertools==0.12.0
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - ansicon==1.89.0
    - ansys-api-dyna==0.4.2
    - ansys-dpf-core==0.13.8
    - ansys-dyna-core==0.8.0
    - ansys-tools-path==0.7.3
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - arrow==1.3.0
    - backoff==2.2.1
    - bitsandbytes==0.41.0
    - blessed==1.21.0
    - boto3==1.37.3
    - botocore==1.37.3
    - chardet==5.2.0
    - click==8.2.1
    - contourpy==1.3.2
    - croniter==1.4.1
    - cycler==0.12.1
    - dateutils==0.6.12
    - deepdiff==6.7.1
    - deepxde==1.10.0
    - docker==6.1.3
    - docstring-parser==0.16
    - editor==1.6.6
    - fastapi==0.115.12
    - fonttools==4.58.0
    - frozenlist==1.6.0
    - fsspec==2023.12.2
    - grpcio==1.73.0
    - hollerith==0.6.0
    - hydra-core==1.3.2
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - inquirer==3.4.0
    - jinxed==1.3.0
    - jmespath==1.0.1
    - joblib==1.5.1
    - jsonargparse==4.40.0
    - lightning==2.2.5
    - lightning-api-access==0.0.5
    - lightning-cloud==0.5.69
    - lightning-fabric==2.5.1.post0
    - lightning-utilities==0.14.3
    - markdown==3.8.2
    - markdown-it-py==3.0.0
    - matplotlib==3.10.3
    - mdurl==0.1.2
    - multidict==6.4.4
    - omegaconf==2.3.0
    - ordered-set==4.1.0
    - pandas==2.2.3
    - propcache==0.3.1
    - protobuf==5.29.5
    - pyaml==25.1.0
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    - pyjwt==2.9.0
    - pyparsing==3.2.3
    - python-multipart==0.0.20
    - pytorch-lightning==2.5.1.post0
    - pytz==2025.2
    - rdflib==7.1.4
    - readchar==4.2.1
    - redis==5.3.0
    - rich==13.9.4
    - runs==1.2.2
    - s3fs==2023.12.2
    - s3transfer==0.11.3
    - scikit-learn==1.6.1
    - scikit-optimize==0.10.2
    - scipy==1.15.3
    - starlette==0.46.2
    - sympy==1.13.1
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.6.0
    - torchaudio==2.5.1
    - torchmetrics==1.7.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - transformations==2025.1.1
    - types-python-dateutil==2.9.0.20250516
    - typeshed-client==2.7.0
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - uvicorn==0.34.2
    - websockets==11.0.3
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xmod==1.8.1
    - yarl==1.20.0
    - zipp==3.23.0
prefix: C:\Users\ecazares3\Anaconda3\envs\pinn311
